Current Certificate is outdated
Joel-hanson/django-aws-eb-deploy pull request #24
Opened 2020-11-18 15:31 UTC by sandy2008

2020-11-19 13:09 UTC, Joel-hanson commented
Thanks for the PR @sandy2008 will merge this as soon I test it.

2020-11-19 13:12 UTC, Joel-hanson commented on Dockerfile
> +RUN sudo apt install ca-certificates
Sudo is not required

2020-11-19 13:13 UTC, Joel-hanson requested changes
Requested changes

2020-11-24 15:14 UTC, sandy2008 reviewed
Thx

2020-12-07 04:23 UTC, merged